### ISSUE TITLE
python Analysis/inter_motivation/select_neurons.py ？

### ISSUE THREAD

**Issue by kkkk-cyber** [wenlai-lavine/sNeuron-TST#1]
No such file

**Comment by wenlai-lavine** [comment]
Sorry, I didn't check the file before. The file is in the ```Analysis``` now.

**Comment by kkkk-cyber** [comment]
Thank you for your reply. I have another question for you: I don't know the difference between task_activation and activation in identify.py. What dataset is task_activation obtained from? Could you please publish this file or dataset?
