### ISSUE TITLE
Question about code and datasets

### ISSUE THREAD

**Issue by A1exRey** [wenlai-lavine/sNeuron-TST#2]
I have a few questions about the code. This line
https://github.com/wenlai-lavine/sNeuron-TST/blob/758682b70e6d9df335ead633b448480444acdc49/Our/gen_contrast_neurons.py#L12
tries to import nonexistent file. I assume the correct option would be `from dola import DoLa #as Con_Neu` ? If not, can you upload a `contra_neurons` file?
Second question is about the experimental setup. In lines 32-36 you load https://github.com/wenlai-lavine/sNeuron-TST/blob/758682b70e6d9df335ead633b448480444acdc49/identify.py#L33 `positive_activation`, `negative_activation `and `positive_task_activation`, `negative_task_activation`. Can you describe the difference between the **_activation** and **_task_activation**?  I didn't find a clear description in the readme or in the paper itself. I'm hypothesising that **_activation** is just activations collected on the formal\informal part of GYAFC, for example. Then **_task_activation** should be the same examples, but with the addition of a prompt to style transfer? Am I right?

**Comment by wenlai-lavine** [comment]
@A1exRey  Thanks for your interest, I have updated and check the code again.
--- ----- 
Sorry, the ```task_activation``` is an initial idea to also add the prompt when identify the neurons, but unfortunately, this doesn't work anymore, so just ignore them. I will also clean up the code latter. Regarding the ```contra_neurons```, yes, this is an important file during decoding in our approach, I am sorry that I forget to upload this file. I will clean up the code then upload it later.
